namespace xamarin_app.Documents
{
    public static class AboutUs
    {
        public static readonly string WelcomeGerman = "Diese App beruht auf dem gedruckten Heft „Migraboarisch – Von uns fia eich. Ein Wegweiser durch den Dialekt“. Dieser Sprachführer wurde im Schuljahr 2016/17 von Kelheimer Schülern entwickelt und möchte Neuankömmlingen jeder Herkunft die sprachliche Ankunft in Bayern erleichtern und das Kennenlernen der bairischen Sprache, der Gebräuche und Lebensphilosophie ermöglichen.\nAuf Basis des Sprachführers haben Studierende der Uni Marburg im SS 2019 und WS 2019/20 diese App entwickelt.Wir haben den Wortschatz um Sprachaufnahmen und Übersetzungen ergänzt und wünschen euch viel Spaß beim Lernen!\n In diesem Sinne: „Welcome to Bavaria!“";
        public static readonly string WelcomeEnglish = "This app is based on the printed booklet „Migraboarisch – Von uns fia eich. Ein Wegweiser durch den Dialekt“. School students from Kelheim completed the phrase book in the 2016/2017 school year. Their intention was to give new arrivals a feel for the language, customs, and philosophy of life in Bavaria.\nIn the summer semester of 2019 and in the winter semester of 2019/2020, students at the University of Marburg developed this app.We added speech recordings and translations of the vocabulary words and phrases.We hope you have fun learning about Bavaria using our app!\nOn that note, „Welcome to Bavaria!“";
        public static readonly string WelcomeCzech = "Tato aplikace vychází z tištěné brožury „Migraboarisch – Von uns fia eich. Ein Wegweiser durch den Dialekt“. Tento jazykový průvodce vznikl ve školním roce 2016/17 a sestavila jej jedna kelheimerská žákyně. Hlavním posláním publikace je usnadnit nově příchozím jakéhokoliv původu jazykový vstup do Bavorska a umožnit jim poznávání bavorského jazyka, zvyků, tradic a životní filozofie.\nAplikaci pak na základě uvedeného průvodce vyvinuli studentky a studenti Univerzity vMarburgu vletním semestru 2018/19 a vzimním semestru 2019/20. Slovní zásobu jsme doplnili o nahrávky a překlady a přejeme vám, abyste se při učení dobře bavili!\nV tomto duchu tedy: „Welcome to Bavaria!“";
        public static readonly string WelcomeArabic = "هذا التطبيق مبني على الكتيب „Migraboarisch – Von uns fia eich. Ein Wegweiser durch den Dialekt“. هذا الدليل اللغوي تم تكوينه من قبل الطلاب من كيلهايم في العام الدراسي 17/2016 وهو يقدم لكل القادمين إلى بافاريا المساعدة في تعلم اللهجة البفارية بل وأيضا تعلم العادات والتقاليد والفلسفة الحياتية البفارية. بناءا على الكتيب اللغوي المذكور أعلاه قام طلبة جامعة ماربورج بتطوير هذا التطبيق في الفصل الدراسي الصيفي 2019 والفصل الشتوي 2019ّ/2020 . لقد أضفنا إلى المفردات اللغوية أيضا تسجيلات صوتية وترجمات إضافية. نتمنى لكم الإستمتاع بالدراسة. و“Welcome to Bavaria!“";

        public static readonly string NoteGerman = "Hinweis: In Bayern werden unterschiedliche Dialekte gesprochen: u.a. Bairisch, Fränkisch und Schwäbisch. Jeder Sprecher kann nur repräsentativ für den Dialekt seines Ortes stehen. Unser Sprecher kommt aus Regensburg und spricht Nordmittelbairisch.";
        public static readonly string NoteEnglish = "Nota bene: Different kinds of dialects are spoken in Bavaria including Bavarian, Franconian, and Swabian. Speakers are only representative for the town or village they come from. Our speaker comes from Regensburg and speaks North Central Bavarian.";
        public static readonly string NoteCzech = "Důležité: V Bavorsku se hovoří různými dialekty: mimo jiné se jedná o nářečí bavorská, franská a švábská. Každý mluvčí tedy může reprezentovat pouze určitý dialekt z oblasti svého původu. Náš mluvčí pochází z Řezna a mluví severostřední bavorštinou.";
        public static readonly string NoteArabic = "ملاحظة : في بفاريا يتم استخدام لهجات مختلفة : منها البافاري والفرانكوني والشفابي . كل متحدث يستطيع فقط أن يمثل لهجة مكان منشئه . المتحدث بالتسجيلات الصوتية المقدمة في هذا التطبيق هو من شمال وسط بافاريا، تحديدا من ريغنسبورغ ويتحدث بافاري وسطي شمالي. ";

        public static readonly string ThanksGerman = "Wir danken der Johann-Andreas-Schmeller-Gesellschaft e.V. für die finanzielle Förderung! Vielen Dank an Melanie Bajrami, Hanni Schnell und Milena Gropp für die Mitarbeit.";
        public static readonly string ThanksEnglish = "We would like to thank the Johann-Andreas-Schmeller-Gesellschaft e.V. for their financial support in addition to Melanie Bajrami, Hanni Schnell, and Milena Gropp for their cooperation.";
        public static readonly string ThanksCzech = "Děkujeme Společnosti Johanna Andrease Schmellera za finanční podporu! Dále patří dík Melanii Bajrami, Hanni Schnell a Mileně Gropp za jejich pomoc a spolupráci.";
        public static readonly string ThanksArabic = "نتقدم بفاضل الشكر لمنظمة Johann-Andreas-Schmeller-Gesellschaft e.V. für لدعمها المادي لنا. نود أن نتقدم أيضا بفاضل الشكرإلى  Melanie Bajrami  و Hanni Schnell و Milena Gropp من أجل تعاونهم .";
    }
}
